### ISSUE TITLE
No module named 'pyperclip'

### ISSUE THREAD

**Issue by Starkium** [somethingcoolmustbehere/dumpPakKey#5]
Traceback (most recent call last):
  File "dumpPakKey.py", line 6, in <module>
ModuleNotFoundError: No module named 'pyperclip'
[72216] Failed to execute script dumpPakKey

**Comment by allcoolthingsatoneplace** [comment]
Win+R, type cmd, hit enter in appeared command prompt

type : pip install pyperclip

assuming that python is installed on your system

**Comment by LEISER307** [comment]
Man, What to do, I have it installed!?
![Сни21312фымок](https://user-images.githubusercontent.com/16767541/104249823-3f9f9400-547d-11eb-8624-fc597587a328.PNG)

I won't understand the meaning of your program if it doesn't work properly!
![Се34фй23инимок](https://user-images.githubusercontent.com/16767541/104250947-c05f8f80-547f-11eb-8a35-fabcbd2c3397.PNG)

**Comment by allcoolthingsatoneplace** [comment]
pip uninstall pyperclip

then install it again

pip install  - - upgrade pip

pip install pyperclip

and if it wont work you can just comment out

using #

in front of 159 line of code...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
